apply plugin: 'eclipse'

description = "dynmap-api"

dependencies {
    compileOnly group: 'org.bukkit', name: 'bukkit', version:'1.7.10-R0.1-SNAPSHOT'
    compileOnly project(":DynmapCoreAPI")
}

jar {
   archiveClassifier  = 'unshaded'
}

shadowJar {
    dependencies {
        include(dependency(":DynmapCoreAPI"))
	}
    destinationDirectory = file '../target'
    archiveClassifier  = ''
}

artifacts {
    archives shadowJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
