pluginManagement {
  repositories {
    gradlePluginPortal()
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://papermc.io/repo/repository/maven-public/" }
  }
}

rootProject.name = 'dynmap-common'

include ':spigot'
include ':bukkit-helper-121-6'
include ':bukkit-helper-121-10'
include ':bukkit-helper-121-11'
include ":bukkit-helper-26-3"
include ':bukkit-helper'
include ':dynmap-api'
include ':DynmapCore'
include ':DynmapCoreAPI'

project(':spigot').projectDir = "$rootDir/spigot" as File
project(':bukkit-helper-121-6').projectDir = "$rootDir/bukkit-helper-121-6" as File
project(':bukkit-helper-121-10').projectDir = "$rootDir/bukkit-helper-121-10" as File
project(':bukkit-helper-121-11').projectDir = "$rootDir/bukkit-helper-121-11" as File
project(":bukkit-helper-26-3").projectDir = "$rootDir/bukkit-helper-26-3" as File
project(':bukkit-helper').projectDir = "$rootDir/bukkit-helper" as File
project(':dynmap-api').projectDir = "$rootDir/dynmap-api" as File
project(':DynmapCore').projectDir = "$rootDir/DynmapCore" as File
project(':DynmapCoreAPI').projectDir = "$rootDir/DynmapCoreAPI" as File
